import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <div id="root">{children}</div>
        <div
          id="modal"
          className="fixed left-[40px] bottom-[60px] w-[300px] h-[300px] bg-hoverRed z-[999] hidden text-red text-xs font-bold border border-red p-[6px]"
        >
          pop up
        </div>
      </body>
    </html>
  );
}
