import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik_Glitch, Audiowide } from "next/font/google";
import "./globals.css";
import PopupForm from "../components/PopupForm";
import CustomCursor from "../components/CustomCursor";
const geistSans = Geist({
  subsets: ["latin"],
  weight: "400", // დაამატე სიმძლავრე
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: "400", // დაამატე სიმძლავრე
});

const rubikGlitch = Rubik_Glitch({
  subsets: ["latin"],
  weight: "400", // დაამატე სიმძლავრე
});
const audiowide = Audiowide({
  subsets: ["latin"],
  weight: "400", // დაამატე სიმძლავრე
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          fontFamily: `${geistSans.style.fontFamily}, ${geistMono.style.fontFamily}, ${rubikGlitch.style.fontFamily}`,
        }}
        className="antialiased bg-black "
      >
        <div id="root" className="font-Audiowide text-[12px] ">
          <CustomCursor />

          {children}
        </div>
        <div
          id="modal"
          className="flex flex-col justify-end fixed bg-black sm:bg-transparent h-screen sm:h-auto sm:left-[20px] bottom-0 sm:bottom-[0px] w-full sm:w-[500px] bg-yellow z-[999] hidden p-[20px]"
        >
          <p className="font-bold text-red text-xl mb-[8px] font-rubik-glitch">
            CONNECT WITH ME
          </p>
          <p className="font-bold text-white text-xs mb-[16px]">
            WANNA CHAT? OR JUST SHARE SOMETHING COOL?
          </p>
          <div className="text-red text-xs font-bold border border-red p-[20px] bg-hoverRed mb-[24px]">
            <PopupForm />
          </div>
          <div className="flex gap-[16px]">
            <button
              type="submit"
              className="w-full bg-red text-black font-bold p-2 "
            >
              SEND MESSAGE [ENTER]
            </button>
            <button className="w-full bg-black text-red font-bold border border-[#b2b7ba] p-2 ">
              DISCARD [ESC]
            </button>
          </div>
        </div>
      </body>
    </html>
  );
}
